const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const OUTPUT_DIR = path.join(__dirname, '..', '..', 'uploads', 'prescriptions');
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

// Generates a simple prescription PDF and returns the relative path (stored on the model).
function generatePrescriptionPdf({ prescriptionId, patientName, doctorName, medicines, testsSuggested, followUpDate }) {
  return new Promise((resolve, reject) => {
    const fileName = `prescription_${prescriptionId}.pdf`;
    const filePath = path.join(OUTPUT_DIR, fileName);
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(18).text('Prescription', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).text(`Patient: ${patientName}`);
    doc.text(`Doctor: ${doctorName}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    doc.fontSize(13).text('Medicines', { underline: true });
    (medicines || []).forEach((m, i) => {
      doc.fontSize(11).text(`${i + 1}. ${m.name}  ${m.dosage || ''}  ${m.duration ? '- ' + m.duration : ''}`);
    });

    if (testsSuggested && testsSuggested.length) {
      doc.moveDown();
      doc.fontSize(13).text('Tests Suggested', { underline: true });
      testsSuggested.forEach((t) => doc.fontSize(11).text(`- ${t}`));
    }

    if (followUpDate) {
      doc.moveDown();
      doc.fontSize(11).text(`Follow-up: ${new Date(followUpDate).toLocaleDateString()}`);
    }

    doc.moveDown(2);
    doc.fontSize(10).fillColor('gray').text('Generated by Clinic Management System', { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(`/uploads/prescriptions/${fileName}`));
    stream.on('error', reject);
  });
}

module.exports = { generatePrescriptionPdf };
