const PDFDocument = require('pdfkit');

// Draws the prescription content onto a PDFKit document.
function renderPrescription(doc, { patientName, doctorName, medicines, testsSuggested, followUpDate }) {
  doc.fontSize(18).text('Prescription', { align: 'center' });
  doc.moveDown();
  doc.fontSize(11).text(`Patient: ${patientName}`);
  doc.text(`Doctor: ${doctorName}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown();

  doc.fontSize(13).text('Medicines', { underline: true });
  (medicines || []).forEach((m, i) => {
    doc.fontSize(11).text(`${i + 1}. ${m.name}  ${m.dosage || ''}  ${m.duration ? '- ' + m.duration : ''}`);
  });

  if (testsSuggested && testsSuggested.length) {
    doc.moveDown();
    doc.fontSize(13).text('Tests Suggested', { underline: true });
    testsSuggested.forEach((t) => doc.fontSize(11).text(`- ${t}`));
  }

  if (followUpDate) {
    doc.moveDown();
    doc.fontSize(11).text(`Follow-up: ${new Date(followUpDate).toLocaleDateString()}`);
  }

  doc.moveDown(2);
  doc.fontSize(10).fillColor('gray').text('Generated by Clinic Management System', { align: 'center' });
}

// Builds the PDF fresh from the given data and streams it to `target`
// (an HTTP response). Nothing is written to disk, so it works on hosts with
// an ephemeral or read-only filesystem (Render, most PaaS) and survives
// restarts/redeploys.
function streamPrescriptionPdf(target, data) {
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(target);
  renderPrescription(doc, data);
  doc.end();
  return doc;
}

module.exports = { streamPrescriptionPdf };
